version: '3'

services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network
    restart: always

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - app-network
    restart: always

  receiver-service:
    build:
      context: ./receiver-service
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/pubsub
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - mongodb
      - redis
    networks:
      - app-network
    restart: always

  listener-service:
    build:
      context: ./listener-service
    ports:
      - "3001:3001"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/pubsub
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - mongodb
      - redis
    networks:
      - app-network
    restart: always

networks:
  app-network:

volumes:
  mongodb_data: